name: Staging CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "staging" ]

permissions:
  contents: read
  packages: write   # GHCR push에 필요

concurrency:
  group: production-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      SUBMODULE_TOKEN: ${{ secrets.SUBMODULE_ACTION_TOKEN }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }} # <owner>/<repo>

    outputs:
      image: ${{ steps.set-image-output.outputs.image }}

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          token: ${{ env.SUBMODULE_TOKEN }}
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle (no tests)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/cozy-mate/cozymate-server:${{ env.IMAGE_TAG }}
          build-args: |
            SPRING_PROFILE=prod
          cache-from: type=gha
          cache-to: type=gha,mode=max

  cd:
    needs: ci
    name: CD
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to HomeServer (Staging Branch)
        if: github.ref == 'refs/heads/staging'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOME_HOST }}
          port: ${{ secrets.HOME_PORT }}
          username: ${{ secrets.HOME_USERNAME }}
          key: ${{ secrets.HOME_SSH_KEY }}
          passphrase: ${{ secrets.HOME_SSH_KEY_PASSPHRASE }}
          script: |
            cd /home/cozymate/deploy
            ./deploy_staging.sh ${{ env.IMAGE_TAG }}